apiVersion: v1
kind: PersistentVolume
metadata:
  name: _name
spec:
  capacity:
    storage: _capacity
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd-_class
  local:
    path: _path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - _host
