apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: jhub
spec:
  storageClassName: "local-hdd-lg"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
